### PR TITLE
Made GamesClient AOT-compatible

### PR DESCRIPTION
**Pull request by szv**
# Pull Request Description

This pull request includes several significant updates to the `Codebreaker.GameAPIs.Client` project, primarily focusing on serialization, logging, and class updates.

## Serialization and Logging Updates

The `Codebreaker.GameAPIs.Client.csproj` file was updated to include `<IsAotCompatible>true</IsAotCompatible>` and `<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>` properties. These changes are aimed at improving the performance and compatibility of the project. The version of `Microsoft.Extensions.Logging.Abstractions` package was also updated to `8.0.1` for `net8.0` to leverage the latest features and improvements.

A new `GamesClientJsonSerializerContext.cs` file was added to handle JSON serialization for various classes. This is a significant design decision aimed at centralizing and improving the serialization process.

## Class Updates

Several classes were updated to improve their functionality and clarity:

- `GamesClientTests.cs`: Updated to use `GameType.Game6x4` instead of `Models.GameType.Game6x4` in the `StartGameAsync` method.
- `GamesClient.cs`: Updated to use `Codebreaker.GameAPIs.Client.Serialization` namespace and to replace `_httpClient` and `s_jsonOptions` with `httpClient` and `GamesClientJsonSerializerContext.Default`.
- `CreateGameResponse.cs`: Updated to include `FieldValues` as a parameter in the `CreateGameResponse` record class.
- `GameInfo.cs`: Updated to include `fieldValues` and `codes` as parameters in the `GameInfo` class. The comments were also updated for better clarity and understanding.
- `GamesQuery.cs`: Updated to use `StringBuilder` for building the query string in the `AsUrlQuery` method.
- `MoveInfo.cs`: Updated to include `guessPegs` and `keyPegs` as parameters in the `MoveInfo` class. The `ToString` method was also updated to use string interpolation.
- `UpdateGameRequest.cs`: Updated to include a `GuessPegs` property.

These changes were made to improve the clarity, maintainability, and performance of the code.

### CODE REVIEW

**Review by christiannagel — CHANGES_REQUESTED** [review]
I'm not sure this runs with .NET 7 clients as well. The test project is .NET 8. 
Change the test project for multi-targeting with .NET 7 and .NET 8, and update the github action to run tests with .NET 7 and .NET 8 when possible.

**Comment by szv** [comment]
I made the unit test project for the GamesClient now a multi-target project (for .NET7 and .NET8).
The tests pass for both frameworks.
The JSON Source Generator was introduced in .NET6, right? What issues do you expect with .NET7?

**Comment by christiannagel** [comment]
for example, init-only properties are not ok with .NET 7, but are ok with .NET 8. The .NET 7 test did not run because there was still an init-only property with the GameInfo.

Now as you change the init-only properties, serialization is ok with .NET 7. But we will not use AOT with .NET 7 anyway.

I also need to verify changes needed with the book before the first "release" of this library.

**Comment by szv** [comment]
Closed in favour of #170.
@szv Add AOT-compatability when migrating from .NET7+8 to .NET8+9

**Pull request closed without merging**
